import 'package:flutter/material.dart';
const kBottomContainerHeight = 80.0;
const kActiveCardColor = Color(0xFF1D1E33);
const kInactiveCardColor = Color(0xFF111328);
const kBottomContainerColor = Color(0xFF1D1E33);
const kTextStyle = TextStyle(fontSize: 18.0, color: Color(0XFF8D8E98));
const kBoldText = TextStyle(fontSize: 50, fontWeight: FontWeight.w900,);
const kLargeText = TextStyle(fontSize: 25, fontWeight: FontWeight.bold,);
const kXLargeText = TextStyle(fontSize:50 , fontWeight: FontWeight.bold,);
const kResultText = TextStyle(color: Color(0xFF24D876), fontSize: 22.0, fontWeight: FontWeight.bold);
const kBMIText = TextStyle(fontSize: 100.0, fontWeight: FontWeight.bold);
const kCommentText = TextStyle(fontSize: 22.0);
const minHeight = 0.0;
const maxHeight = 300.0;